ARG TAG=1.23

FROM golang:$TAG

WORKDIR /app

# Install packages
RUN apt update && sudo apt upgrade \
    && \
    set -eux; \
    # Packages to install
    apt install -y \
    git \
    rsync \
    && \
    # Clean out directories that don't need to be part of the image
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && \
    # Install needed Go tooling \
    go install github.com/go-task/task/v3/cmd/task@latest \
    && \
    go install github.com/a-h/templ/cmd/templ@latest \
    && \
    go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest \
    && \
    go install github.com/delaneyj/toolbelt/sqlc-gen-zombiezen@latest \
    && \
    go install golang.org/x/tools/cmd/goimports@latest \
    && \
    # Make this a safe .git directory
    git config --global --add safe.directory /app

ENTRYPOINT ["/bin/sh"]